# Generated by Django 3.2.6 on 2021-08-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='motivo',
            field=models.CharField(default='visita', max_length=50),
        ),
    ]
