# Generated by Django 3.2.6 on 2021-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registro_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='motivo',
            field=models.CharField(max_length=50),
        ),
    ]
